version: "3"
services:
  decidim:
    image: ghcr.io/decidim/decidim:0.28.1
    container_name: container_decidim
    entrypoint: ["/code/vendor/hello-world.sh"]
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    ports:
      - 3000:3000
    volumes:
      - /tmp/rails_storage:/code:storage
      - ./scripts:/code/vendor
    environment:
      - TZ=Europe/Madrid
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - SECRET_KEY_BASE=yoursecretkeyhere
      - RAILS_ENV=production
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - SMTP_USERNAME=smtpusernamehere
      - SMTP_PASSWORD=smtppasswordhere
      - SMTP_ADDRESS=smtpaddresshere
      - SMTP_DOMAIN=smtpdomainhere
    links:
      - pg
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis:
    image: redis
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx_custom
    build:
      context: .
      dockerfile: nginx.Dockerfile
    depends_on:
      - decidim
      - pg
      - redis
    ports:
      - 443:443
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  pg-data: {}
  redis-data: {}
